### ISSUE TITLE
you can use switch case and than you check `start` on lowercase and uppercase you can convert to lowercase or uppercase first

### ISSUE THREAD

**Issue by Arif9878** [smilelikeshit/cli-start-stop-instance-aws-gcp-do#1]
https://github.com/smilelikeshit/cli-start-stop-instance-aws-gcp-do/blob/72e15e22f32975e32da457ef73555b9662d3363f/cmd/aws.go#L34

**Comment by firmanJS** [comment]
Yes I agree, it's better to convert to lowercase first or uppercase @smilelikeshit

**Comment by smilelikeshit** [comment]
https://github.com/smilelikeshit/cli-start-stop-instance-aws-gcp-do/pull/3

@firmanJS @Arif9878

**Comment by smilelikeshit** [comment]
https://github.com/smilelikeshit/cli-start-stop-instance-aws-gcp-do/pull/3

has alread fix by fritend @sandisunandar99 
@firmanJS @Arif9878
